#! /bin/sh
set -e

write_cache()
{
if [ -x /usr/bin/gtk-update-icon-cache ]; then
    if ! gtk-update-icon-cache --force --quiet /usr/share/icons/gnome; then
        echo "WARNING: icon cache generation failed"
    fi
fi
}

if [ "$1" = "triggered" ]; then
    write_cache
    exit 0
fi

SIZES=$(ls /usr/share/icons/gnome/*/places | sed -rn 's,^.*/([0-9]+)x[0-9]+/.*$,\1,p' | grep -v 32)

# use the 32x32 icon as start and slave all other sizes
( while read name prio; do
    command="update-alternatives --install /usr/share/icons/gnome/32x32/places/start-here.png start-here-32.png /usr/share/icons/gnome/32x32/places/$name.png $prio"
    for s in $SIZES; do
      command="$command --slave /usr/share/icons/gnome/${s}x${s}/places/start-here.png start-here-${s}.png /usr/share/icons/gnome/${s}x${s}/places/$name.png"
    done
    $command
  done ) << EOF
debian-swirl 30
gnome-foot 20
swirl-foot 20
EOF

write_cache

#DEBHELPER#
